# Generated by Django 4.2.16 on 2024-12-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=50, verbose_name='nome organizzatore')),
                ('organizer_description', models.TextField(verbose_name='descrizione')),
                ('organizer_email', models.EmailField(max_length=254, verbose_name='email')),
                ('organizer_phone', models.CharField(max_length=15, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'organizzatore',
                'verbose_name_plural': 'organizzatori',
            },
        ),
        migrations.CreateModel(
            name='TypeOfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_types', models.CharField(max_length=50, verbose_name='tipo di evento')),
            ],
            options={
                'verbose_name': 'tipo di evento',
                'verbose_name_plural': 'tipi di evento',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_slug', models.SlugField(max_length=100)),
                ('event_description', models.TextField(verbose_name='descrizione')),
                ('event_creation_date', models.DateTimeField(auto_now_add=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='TicketStore.organizer')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_type', to='TicketStore.typeofevent')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventi',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='AvailableDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='data inizio')),
                ('date_to', models.DateField(verbose_name='data fine')),
                ('related_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_date', to='TicketStore.event')),
            ],
            options={
                'verbose_name': 'data disponibile',
                'verbose_name_plural': 'date disponibili',
            },
        ),
    ]
